
volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: fyrno/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/backend_media

  frontend:
    image: fyrno/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    image: fyrno/kittygram_nginx
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/mediafiles
    ports:
      - 9000:80
